In [1]:
range(0,10)

range(0, 10)

In [3]:
a = list(range(0,10))

In [4]:
import numpy as np

In [5]:
a = np.array(a)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c = a.copy()

In [8]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
c[0] = 1111

In [10]:
c

array([1111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [11]:
d = c[0:5]

In [12]:
d

array([1111,    1,    2,    3,    4])

In [13]:
d = 2222

In [14]:
d

2222

In [15]:
d = c[0:5]

In [16]:
d

array([1111,    1,    2,    3,    4])

In [17]:
c

array([1111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [18]:
d[:] = 2222

In [19]:
d

array([2222, 2222, 2222, 2222, 2222])

In [20]:
 c

array([2222, 2222, 2222, 2222, 2222,    5,    6,    7,    8,    9])